library(shiny)

# Define UI for dataset viewer application
shinyUI(fluidPage(
  tabsetPanel(
    tabPanel("Batting Statistics for Most Valuable Players",dataTableOutput("mvp_table")), 
    tabPanel("Pitching Statistics for Cy Young Award Winners", dataTableOutput("cy_table")), 
    tabPanel(title = "Home Run Hitters Scatterplot",pageWithSidebar(headerPanel("Home Run Hitters Scatterplot"),
      sidebarPanel(sliderInput("mindate",                                                              "Beginning Year:", 
                   min = 1985,
                   max = 2006,
                   value = 1985, sep = ''), 
                   
                   sliderInput("maxdate",
                   "Ending Year:",
                   min = 1986,
                   max = 2007,
                   value = 2007, sep = '')), mainPanel(plotOutput("scatplot")))),
    tabPanel(title = "Histogram for Hits by Team and Year", sidebarLayout(sidebarPanel("Teams and Years",
      selectInput("teams",                                                                             "Select Team(s):",
                          c("Anaheim Angels (1997-2004)" = "ANA",
                            "Diamondbacks" = "ARI",
                            "Braves" = "ATL",
                            "Orioles" = "BAL",
                            "Red Sox" = "BOS",
                            "White Sox" = "CHA",
                            "Cubs" = "CHN",
                            "Reds" = "CIN",
                            "Indians" = "CLE",
                            "Rockies" = "COL",
                            "Tigers" = "DET",
                            "Florida Marlins (1986-2012)" = "FLO",
                            "Astros" = "HOU",
                            "Royals" = "KCA",
                            "Los Angeles Angels(2005-2014)" = "LAA",
                            "Dodgers" = "LAN",
                            "Miami Marlins (2012-2014)" = "MIA",
                            "Brewers" = "MIL",
                            "Twins" = "MIN",
                            "Yankees" = "NYA",
                            "Mets" = "NYN",
                            "Athletics" = "OAK",
                            "Phillies" = "PHI",                                                                  "Pirates" = "PIT",
                            "Padres" = "SDN",
                            "Mariners" = "SEA",
                            "Giants" = "SFN",
                            "Cardinals" = "SLN",
                            "Rays" = "TBA",
                            "Rangers" = "TEX",
                            "Blue Jays" = "TOR",
                            "Nationals (2005-2014)" = "WAS"
                            )),
      numericInput("years", "Select Year (1986-2014): ", 1997, min = 1986, max = 2014, step = 1),
      actionButton(inputId = "clicks", label = "Run")),
      mainPanel("Histogram for Hits by Team and Year",plotOutput("hist")))))
    ))